// Generated by CoffeeScript 1.6.2
/*
Copyright (C) 2013, Bill Burdick

(licensed with ZLIB license)

This software is provided 'as-is', without any express or implied
warranty. In no event will the authors be held liable for any damages
arising from the use of this software.

Permission is granted to anyone to use this software for any purpose,
including commercial applications, and to alter it and redistribute it
freely, subject to the following restrictions:

1. The origin of this software must not be misrepresented; you must not
claim that you wrote the original software. If you use this software
in a product, an acknowledgment in the product documentation would be
appreciated but is not required.

2. Altered source versions must be plainly marked as such, and must not be
misrepresented as being the original software.

3. This notice may not be removed or altered from any source distribution.
*/


(function() {
  var Cons, Nil, NilClass, addListProto, checkList, cons, first, len, list, makeList, rest, root, _,
    __slice = [].slice;

  root = module.exports = require('./base');

  _ = require('./lodash.min');

  list = function() {
    var args;

    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return makeList(0, args);
  };

  makeList = function(index, elements) {
    if (index < elements.length) {
      return cons(elements[index], makeList(index + 1, elements));
    } else {
      return Nil;
    }
  };

  cons = function(a, b) {
    return addListProto(function(f) {
      return f(a, b);
    });
  };

  addListProto = function(l) {
    l.__proto__ = Cons.prototype;
    return l;
  };

  first = function(l) {
    return checkList(l, function() {
      return l(function(a, b) {
        return a;
      });
    });
  };

  rest = function(l) {
    return checkList(l, function() {
      return l(function(a, b) {
        return b;
      });
    });
  };

  checkList = function(l, cont) {
    if (l instanceof Cons) {
      return cont();
    } else {
      throw new Error("Not a list!");
    }
  };

  len = function(l) {
    if (l === Nil) {
      return 0;
    } else {
      return 1 + len(rest(l));
    }
  };

  Cons = (function() {
    function Cons() {}

    Cons.prototype.toString = function() {
      return "List [" + (this.elements(false)) + "]";
    };

    Cons.prototype.elements = function(comma) {
      return "" + (comma ? ', ' : '') + (first(this)) + (rest(this).elements(true));
    };

    return Cons;

  })();

  NilClass = (function() {
    function NilClass() {}

    NilClass.prototype.toString = function() {
      return "List []";
    };

    NilClass.prototype.elements = function(comma) {
      return "";
    };

    return NilClass;

  })();

  Nil = new NilClass;

  root.list = list;

  root.cons = cons;

  root.Nil = Nil;

  root.first = first;

  root.rest = rest;

  root.len = len;

}).call(this);

/*
//@ sourceMappingURL=lists.map
*/
